#!/bin/csh

source /opt/ngat/etc/cshrc
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/x_setup


set POLICY = "-Djava.security.policy=/occ/tmp/policy.dat"

$JAVA_HOME/bin/java $POLICY  ngat.sms.test.FindInstruments
