#!/bin/csh

# Starts up a ScheduleDespatcher and ExecutionUpdateManager

source /opt/ngat/etc/cshrc

source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/x_setup

java ngat.sms.test.SimpleExecutorTest 
#--ref --host --port

